#!/usr/bin/env node

var fs = require('fs');
var path = require('path');
var cssmin = require('cssmin');

module.exports = function(indir, outfile, cb) {
    var styles = {};
    var files = fs.readdirSync(indir);
    files.forEach(function(file) {
        var filePath = path.join(indir, file);
        var name = file.match(/(.*)\.css/)
        if(!name) {
        	return;
        }
        var original_data = fs.readFileSync(filePath);
        styles[name.pop()] = cssmin(original_data.toString());
    });

    fs.writeFileSync(outfile, 'module.exports = ' + JSON.stringify(styles));

    cb();
};

if (require.main === module) {
    var path = require('path');
    var indir = path.join(process.cwd(), process.argv[2]);
    var outfile = path.join(process.cwd(), process.argv[3]);

    module.exports(indir, outfile, console.log.bind(console, 'Exported styles '+indir));
}