#!/usr/bin/env node

var fs = require('fs');
var path = require('path');

module.exports = function(infile, outfile, cb) {
	var name = path.basename(infile).match(/(.*?)\./).pop();
    var original_data = fs.readFileSync(infile, 'utf-8');
    fs.writeFileSync(outfile, 'module.exports = {' + name + ': ' + JSON.stringify(original_data)+' }');

    cb();
};

if (require.main === module) {
    var path = require('path');
    var infile = path.join(process.cwd(), process.argv[2]);
    var outfile = path.join(process.cwd(), process.argv[3]);

    module.exports(infile, outfile, console.log.bind(console, 'Exported style '+infile));
}